num = int(input("Digite um número: "))
n1 = str(num)
print(f"Analisando o número {num}.")
print(f"Unidade: {n1[3]}")
print(f"Dezena: {n1[2]}")
print(f"Centena: {n1[1]}")
print(f"Milhar: {n1[0]}")